### ISSUE TITLE
Terasort error 

### ISSUE THREAD

**Issue by li7hui** [ehiggs/spark-terasort#17]
Hi, 
I am trying to run the spark terasort app on a RoCE network. The teragen code works fine, however the terasort code fails with following error msg:
![error2](https://user-images.githubusercontent.com/1718938/45264488-df236680-b42c-11e8-9652-a3b1910582e2.png)

![error3](https://user-images.githubusercontent.com/1718938/45264497-01b57f80-b42d-11e8-805f-b3550864ee64.png)
all these error msg comes from the spark job history server.

**Comment by ehiggs** [comment]
Hi! Thanks for trying this out on a RoCE network. 

It looks like the erorr takes place in the RDMA code: startRdmaNodeIfMissing. The assert failing appears to be [this](https://github.com/Mellanox/SparkRDMA/blob/master/src/main/scala/org/apache/spark/shuffle/rdma/RdmaShuffleManager.scala#L278):

```scala
assume(!isDriver)
```

My guess is that somehow you're running on the driver? Maybe you're running on a single node to test this out, but it turns out it's the driver node? I'm really not sure since I no longer have access to RDMA systems.

**Comment by li7hui** [comment]
Hi,
I got the RDMA Spark from Mellanox : https://github.com/Mellanox/SparkRDMA

When I comment out the RDMA component, the Spark Terasort code run successfully. So the problem problem lie in RDMA Spark. 

Many thanks for your reply.
